<?php
/**
 * Filtered block's which should be present on posts.
 * Post-type - Product, Applications, Post.
 * And common which will be included in all.
 *
 * @package OneNovantaTheme
 */

return [
	'product'             => [
		'one-novanta/accessories',
		'one-novanta/cad-modal-item',
		'one-novanta/cad-modals',
		'one-novanta/cart-button',
		'one-novanta/components',
		'one-novanta/documents',
		'one-novanta/notice',
		'one-novanta/product-search',
		'one-novanta/product-variation-content',
		'one-novanta/product-variation-related-modules',
		'one-novanta/related-modules',
		'one-novanta/related-products',
		'one-novanta/single-product-detail',
		'one-novanta/specification-item',
		'one-novanta/specifications',
		'yoast-seo/breadcrumbs',
		'one-novanta/card',
		'one-novanta/cards',
		'one-novanta/section-50-50-question',
		'one-novanta/media-text-cover',
		'one-novanta/section',
		'one-novanta/section-content',
		'one-novanta/section-heading',
		'one-novanta/tab-item',
		'one-novanta/tabs',
		'core/block',
		'core/list-item',
		'core/pattern',
		'core/separator',
		'core/video',
		'yoast-seo/estimated-reading-time',
		'woocommerce/add-to-cart-form',
	],
	'novanta_application' => [
		'yoast-seo/breadcrumbs',
		'core/block',
		'core/list-item',
		'core/pattern',
		'core/video',
		'yoast-seo/estimated-reading-time',
		'novanta/estimated-reading-time',
	],
	'post'                => [
		'yoast-seo/breadcrumbs',
		'yoast-seo/estimated-reading-time',
		'novanta/estimated-reading-time',
	],
	'commonBlocks'        => [
		'core/paragraph',
		'core/heading',
		'core/buttons',
		'core/button',
		'core/list',
		'core/group',
		'core/separator',
		'core/embed',
		'core/gallery',
		'core/image',
		'core/video',
		'core/query',
		'core/site-logo',
		'core/social-links',
		'core/social-link',
		'core/cover',
		'core/list-item',
		'core/search',
		'gravityforms/form',
		'core/page-list',
		'core/navigation',
		'core/navigation-link',
		'core/navigation-submenu',
	],
];
